# Generated by Django 4.2.1 on 2023-10-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='last_name',
        ),
    ]
